const citylist = {
    Ampara: [
        "Ampara",
        "Kalmunai",
        "Akkaraipattu",
        "Sainthamaruthu",
        "Sammanthurai",
        "Dehiattakandiya",
        "Uhana",
        "Pottuvil",
        "Thirukkovil",
        "Mahaoya",
    ],
    Anuradhapura: [
        "Anuradhapura",
        "Kekirawa",
        "Medawachchiya",
        "Thambuttegama",
        "Eppawala",
        "Mihintale",
        "Nochchiyagama",
        "Padaviya",
        "Horowpothana",
        "Rambewa",
    ],
    Badulla: [
        "Badulla",
        "Bandarawela",
        "Haputale",
        "Ella",
        "Mahiyanganaya",
        "Welimada",
        "Passara",
        "Hali-Ela",
        "Diyatalawa",
        "Meegahakiula",
    ],
    Batticaloa: [
        "Batticaloa",
        "Kattankudy",
        "Valachchenai",
        "Eravur",
        "Kaluwanchikudy",
        "Vavunathivu",
        "Arayampathy",
        "Kalkudah",
    ],
    Colombo: [
        "Colombo",
        "Dehiwala-Mount Lavinia",
        "Moratuwa",
        "Maharagama",
        "Kesbewa",
        "Kaduwela",
        "Homagama",
        "Nugegoda",
        "Sri Jayawardenepura Kotte",
    ],
    Galle: [
        "Galle",
        "Hikkaduwa",
        "Ambalangoda",
        "Weligama",
        "Unawatuna",
        "Karapitiya",
        "Elpitiya",
        "Ahangama",
    ],
    Gampaha: [
        "Gampaha",
        "Negombo",
        "Kelaniya",
        "Ragama",
        "Wattala",
        "Ja-Ela",
        "Minuwangoda",
        "Divulapitiya",
        "Mirigama",
        "Nittambuwa",
    ],
    Hambantota: [
        "Hambantota",
        "Tangalle",
        "Tissamaharama",
        "Beliatta",
        "Kataragama",
        "Sooriyawewa",
        "Weeraketiya",
        "Ambalantota",
        "Walasmulla",
    ],
    Jaffna: [
        "Jaffna",
        "Nallur",
        "Point Pedro",
        "Chavakachcheri",
        "Velanai",
        "Karainagar",
        "Kodikamam",
        "Kankesanthurai",
        "Delft",
    ],
    Kalutara: [
        "Kalutara",
        "Panadura",
        "Horana",
        "Beruwala",
        "Wadduwa",
        "Matugama",
        "Aluthgama",
        "Agalawatta",
        "Bandaragama",
    ],
    Kandy: [
        "Kandy",
        "Gampola",
        "Nawalapitiya",
        "Peradeniya",
        "Katugastota",
        "Digana",
        "Pilimathalawa",
        "Galaha",
        "Kadugannawa",
    ],
    Kegalle: [
        "Kegalle",
        "Mawanella",
        "Rambukkana",
        "Warakapola",
        "Bulathkohupitiya",
        "Deraniyagala",
        "Yatiyanthota",
        "Aranayake",
    ],
    Kilinochchi: [
        "Kilinochchi",
        "Poonakary",
        "Paranthan",
        "Kandawalai",
        "Karachchi",
    ],
    Kurunegala: [
        "Kurunegala",
        "Kuliyapitiya",
        "Wariyapola",
        "Maho",
        "Narammala",
        "Pannala",
        "Polgahawela",
        "Alawwa",
        "Mawathagama",
    ],
    Mannar: ["Mannar", "Murunkan", "Thalaimannar", "Pesalai"],
    Matale: [
        "Matale",
        "Dambulla",
        "Sigiriya",
        "Galewela",
        "Ukuwela",
        "Rattota",
        "Pallepola",
    ],
    Matara: [
        "Matara",
        "Weligama",
        "Dickwella",
        "Hakmana",
        "Devinuwara",
        "Akuressa",
        "Kamburupitiya",
        "Mirissa",
    ],
    Monaragala: [
        "Monaragala",
        "Wellawaya",
        "Bibile",
        "Buttala",
        "Kataragama",
        "Siyambalanduwa",
        "Medagama",
        "Tanamalwila",
    ],
    Mullaitivu: [
        "Mullaitivu",
        "Puthukudiyiruppu",
        "Oddusuddan",
        "Maritimepattu",
        "Thunukkai",
    ],
    "Nuwara Eliya": [
        "Nuwara Eliya",
        "Hatton",
        "Talawakelle",
        "Ginigathena",
        "Ramboda",
        "Nanu Oya",
        "Pundaluoya",
    ],
    Polonnaruwa: [
        "Polonnaruwa",
        "Hingurakgoda",
        "Medirigiriya",
        "Kaduruwela",
        "Dimbulagala",
        "Welikanda",
    ],
    Puttalam: [
        "Puttalam",
        "Chilaw",
        "Wennappuwa",
        "Mundel",
        "Anamaduwa",
        "Nattandiya",
        "Dankotuwa",
        "Kalpitiya",
    ],
    Ratnapura: [
        "Ratnapura",
        "Embilipitiya",
        "Balangoda",
        "Kuruwita",
        "Kahawatta",
        "Pelmadulla",
        "Godakawela",
        "Opanayake",
    ],
    Trincomalee: [
        "Trincomalee",
        "Kinniya",
        "Mutur",
        "Kantale",
        "Seruwila",
        "China Bay",
        "Nilaveli",
    ],
    Vavuniya: ["Vavuniya", "Nedunkeni", "Vavuniya South", "Cheddikulam"],
};




export default citylist;