import Image from "next/image";
import { NextUIProvider } from "@nextui-org/react";
import Head from "next/head";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  favicon: "https://nextui.org/favicon.ico",
};

export default function Home() {



  return (
    <NextUIProvider>

      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1>main page</h1>
      </main>
    </NextUIProvider>
  );
}
